config/routes.rb
# some bullshit comment just so things will be different

Rubava::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  resources :involvements
  resources :projects
  resources :members
  resources :users
  resources :sessions
  root :to => 'home#index'
end

app/models/involvement.rb
class Involvement < ActiveRecord::Base
  attr_accessible :contributions, :member_id, :project_id, :role
  belongs_to :member
  belongs_to :project
end

app/controllers/involvements_controller.rb
class InvolvementsController < ApplicationController
  # GET /involvements
  # GET /involvements.json
  def index
    @involvements = Involvement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @involvements }
    end
  end

  # GET /involvements/1
  # GET /involvements/1.json
  def show
    @involvement = Involvement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @involvement }
    end
  end

  # GET /involvements/new
  # GET /involvements/new.json
  def new
    @involvement = Involvement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @involvement }
    end
  end

  # GET /involvements/1/edit
  def edit
    @involvement = Involvement.find(params[:id])
  end

  # POST /involvements
  # POST /involvements.json
  def create
    @involvement = Involvement.new(params[:involvement])

    respond_to do |format|
      if @involvement.save
        format.html { redirect_to @involvement, notice: 'Involvement was successfully created.' }
        format.json { render json: @involvement, status: :created, location: @involvement }
      else
        format.html { render action: "new" }
        format.json { render json: @involvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /involvements/1
  # PUT /involvements/1.json
  def update
    @involvement = Involvement.find(params[:id])

    respond_to do |format|
      if @involvement.update_attributes(params[:involvement])
        format.html { redirect_to @involvement, notice: 'Involvement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @involvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /involvements/1
  # DELETE /involvements/1.json
  def destroy
    @involvement = Involvement.find(params[:id])
    @involvement.destroy

    respond_to do |format|
      format.html { redirect_to involvements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/views/involvements/_form.html.erb
<%= form_for(@involvement) do |f| %>
  <% if @involvement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@involvement.errors.count, "error") %> prohibited this involvement from being saved:</h2>

      <ul>
      <% @involvement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :contributions %><br />
    <%= f.text_area :contributions %>
  </div>
  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/involvements/edit.html.erb
<% if current_user %>
<h1>Editing involvement</h1>

<%= render 'form' %>

<%= link_to 'Show', @involvement %> |
<%= link_to 'Back', involvements_path %>
<% else %>
NOPE NOPE NOPE
<% end %>

app/views/involvements/index.html.erb
<h1>Listing involvements</h1>

<table>
  <tr>
    <th>Role</th>
    <th>Contributions</th>
    <th>Member</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @involvements.each do |involvement| %>
  <tr>
    <td><%= involvement.role %></td>
    <td><%= involvement.contributions %></td>
    <td><%= involvement.member_id %></td>
    <td><%= involvement.project_id %></td>
    <td><%= link_to 'Show', involvement %></td>
    <td><%= link_to 'Edit', edit_involvement_path(involvement) %></td>
    <td><%= link_to 'Destroy', involvement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Involvement', new_involvement_path %>

app/views/involvements/new.html.erb
<% if current_user %>
<h1>New involvement</h1>

<%= render 'form' %>

<%= link_to 'Back', involvements_path %>
<% else %>
STEEEEEEEEEERIKE
<% end %>

app/views/involvements/show.html.erb
<% if current_user %>
<p id="notice"><%= notice %></p>

<p>
  <b>Role:</b>
  <%= @involvement.role %>
</p>

<p>
  <b>Contributions:</b>
  <%= @involvement.contributions %>
</p>

<p>
  <b>Member:</b>
  <%= @involvement.member_id %>
</p>

<p>
  <b>Project:</b>
  <%= @involvement.project_id %>
</p>

<%= link_to 'Destroy', @involvement, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Edit', edit_involvement_path(@involvement) %> |
<%= link_to 'Back', involvements_path %>
<% else %>
YER OUT
<% end %>