config/routes.rb
# some bullshit comment just so things will be different

Rubava::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"  
  get "sign_up" => "users#new", :as => "sign_up"
  resources :involvements
  resources :projects
  resources :members
  resources :users
  resources :sessions
  root :to => 'home#index'
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :biography, :email, :fname, :homepage, :leftHanded, :lname, :twitter
  has_many :involvements
  has_many :projects, :through => :involvements
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'First Name' %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label 'Last Name' %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label 'Left Handed?' %><br />
    <%= f.check_box :leftHanded %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :biography %><br />
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Rubava Members</h1>
<br>
<div>
    <% @members.each do |member| %>
            <p><%= link_to member.fname, member%></p>
    <% end %>
</div>
<br />
<% if current_user %>
<%= link_to 'New Member', new_member_path %>
<% end %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <%= gravatar_image_tag(@member.email) %>
  <%= image_tag gravatar_url_for @member.email %>
  <p>
    <h1><%= @member.fname %> <%= @member.lname %></h1>
    <% if @member.leftHanded? %>
      <h2>"lefty"</h2>
    <% end %>
  </p>
  <br>
  <p>
    <%= @member.biography %>
  </p>
  <br>
  <p>
    <% @member.involvements.each do |involvement| %>
    <div class="bordered">
      <h2><%= link_to involvement.project.name, involvement.project %></h2>
      <b><%= involvement.role %></b><br>
      <%= involvement.contributions%>
    </div>
  </p>
    <% end %>
  <br>
  <p>
    <%= mail_to @member.email %>
  </p>

  <p>
    <b>Twitter:</b>
    <%= @member.twitter %>
  </p>

  <p>
    <b>Homepage:</b>
    <%= link_to @member.homepage,@member.homepage %>
  </p>
</div>
<% if current_user %>
<%= link_to 'Edit', edit_member_path(@member) %> |
<% end %>
<%= link_to 'Back', members_path %>